version: '3.9'
services:
  app:
    container_name: hugo
    image: klakegg/hugo:ext-ubuntu
    command: server -s /src/my-site/
    volumes:
            - ".:/src"
    ports:
            - "1313:1313"
